### ISSUE TITLE
Please support connections over unix domain sockets

### ISSUE THREAD

**Issue by mahkoh** [jbg/tokio-postgres-rustls#6]
The function make_tls_connect is called unconditionally for all connections. However, if the user chooses `SslMode::Disable`, rust-postgres will not make further calls into the TLS library. postgres-openssl never fails make_tls_connect. This allows the same connector to be used with UDS connections and TCP connections. Note that make_tls_connect will always be called with the empty hostname for UDS connections. Since postgres-rustls fails early, it cannot be used transparently with all connection strings.

**Comment by mahkoh** [comment]
Please also add support for 0.5 as many libraries libraries still depend on tokio 0.2.

**Comment by mahkoh** [comment]
https://github.com/mahkoh/tokio-postgres-rustls/commit/4807554f6493b60c9faba43966fb6ec1bd2bac48

**Comment by jbg** [comment]
Thanks for the report, and thanks for the commit that resolves the issue. I'm going to do a little analysis to see whether we can simultaneously improve error reporting in this case (we currently swallow the error if the hostname is invalid and just report InvalidInput, and it will become even less clear if the error is reported later).

I'll resolve this in 0.8.0.

I won't be maintaining multiple branches for different `tokio` versions. For anyone using libraries that still have not upgraded to 0.2, there are compatibility solutions like `tokio-compat-02`.

**Comment by jbg** [comment]
I decided to punt on improving the error reporting for now, so this is released in 0.8.0, which is now on crates.io. Thanks!
