### ISSUE TITLE
Support rustls 0.20

### ISSUE THREAD

**Issue by la-urre** [jbg/tokio-postgres-rustls#9]
Hello! First thanks for writing this useful library

rustls 0.20 is out for a few weeks and comes with breaking changes, with a new way to build `ClientConfig`s (using a builder) and the ClientConfig type being moved to the client create. Is there any plan to make this lib work with the latest version ?

**Comment by jbg** [comment]
Just merged #10 which updates `rustls`. v0.9.0 about to hit crates.io.
